// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tbpaxerxduliqmuiuhym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRicGF4ZXJ4ZHVsaXFtdWl1aHltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MjMyNDIsImV4cCI6MjA1MTQ5OTI0Mn0.0Rjg9kn2nsycxvuX3wxo4-gGBTsi1wRK0c7MWr5MpZQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);